<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260830162301 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "app_user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, country_code VARCHAR(2) NOT NULL, latitude NUMERIC(10, 7) NOT NULL, longitude NUMERIC(10, 7) NOT NULL, is_starting_city BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE daily_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, challenge_date DATE NOT NULL, initial_radius INT NOT NULL, starting_city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_560D904BA33130FC ON daily_challenge (challenge_date)');
        $this->addSql('CREATE INDEX IDX_560D904B3C70C2C2 ON daily_challenge (starting_city_id)');
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, score INT NOT NULL, played_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration_sec INT NOT NULL, max_radius DOUBLE PRECISION NOT NULL, current_round INT NOT NULL, attempts_left INT NOT NULL, user_id INT NOT NULL, daily_challenge_id INT DEFAULT NULL, starting_city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_232B318CA76ED395 ON game (user_id)');
        $this->addSql('CREATE INDEX IDX_232B318C157E51E0 ON game (daily_challenge_id)');
        $this->addSql('CREATE INDEX IDX_232B318C3C70C2C2 ON game (starting_city_id)');
        $this->addSql('CREATE TABLE stats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, games_played INT NOT NULL, high_score INT NOT NULL, daily_streak INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_574767AAA76ED395 ON stats (user_id)');
        $this->addSql('CREATE TABLE subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan_type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pay_id VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A3C664D3A76ED395 ON subscription (user_id)');
        $this->addSql('ALTER TABLE daily_challenge ADD CONSTRAINT FK_560D904B3C70C2C2 FOREIGN KEY (starting_city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318CA76ED395 FOREIGN KEY (user_id) REFERENCES "app_user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C157E51E0 FOREIGN KEY (daily_challenge_id) REFERENCES daily_challenge (id)');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C3C70C2C2 FOREIGN KEY (starting_city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stats ADD CONSTRAINT FK_574767AAA76ED395 FOREIGN KEY (user_id) REFERENCES "app_user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3A76ED395 FOREIGN KEY (user_id) REFERENCES "app_user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE daily_challenge DROP CONSTRAINT FK_560D904B3C70C2C2');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318CA76ED395');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C157E51E0');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C3C70C2C2');
        $this->addSql('ALTER TABLE stats DROP CONSTRAINT FK_574767AAA76ED395');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3A76ED395');
        $this->addSql('DROP TABLE "app_user"');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE daily_challenge');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE stats');
        $this->addSql('DROP TABLE subscription');
    }
}
